{
 "title": "Docker logs",
 "time": { "from": "now-3h", "to": "now" },
 "refresh": "1m",
 "panels": [
  {
   "title": "Container error rate [10m]",
   "type": "stat",
   "gridPos": { "h": 12, "w": 5, "x": 0, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(rate({job=\"containerlogs\"} |~ `(?i)Fail|Error|Bug|Drop|Close` != `info` [10m])) / sum(rate({job=\"containerlogs\"} [10m]))",
     "legendFormat": "Error rate"
    }
   ]
  },
  {
   "title": "Log errors per container [auto]",
   "type": "heatmap",
   "gridPos": { "h": 12, "w": 19, "x": 5, "y": 0 },
   "targets": [
    {
     "expr": "sum by(container_name) (count_over_time({job=\"containerlogs\"} |~ `(?i)Error|Fail` !~ `(?i)info` [$__auto]))",
     "legendFormat": "{{container_name}}"
    }
   ]
  },
  {
   "title": "Log count by status [auto]",
   "type": "barchart",
   "gridPos": { "h": 10, "w": 11, "x": 0, "y": 12 },
   "targets": [
    {
     "expr": "sum(count_over_time({job=\"containerlogs\"} |~ `(?i)Success` [$__auto]))",
     "legendFormat": "Success"
    },
    {
     "expr": "sum(count_over_time({job=\"containerlogs\"} |~ `(?i)Fail|(?i)Error` !~ `(?i)info` [$__auto]))",
     "legendFormat": "Error"
    },
    {
     "expr": "sum(count_over_time({job=\"containerlogs\"} |~ `(?i)Warning` [$__auto]))",
     "legendFormat": "Warning"
    },
    {
     "expr": "sum(count_over_time({job=\"containerlogs\"} |~ `(?i)Info` [$__auto]))",
     "legendFormat": "Info"
    }
   ]
  },
  {
   "title": "Container log rate [10m]",
   "type": "state-timeline",
   "gridPos": { "h": 10, "w": 13, "x": 11, "y": 12 },
   "targets": [
    {
     "expr": "sum by(container_name) (rate({job=\"containerlogs\"} [10m]))",
     "legendFormat": "{{container_name}}"
    }
   ]
  },
  {
   "title": "Last error logs from containers",
   "type": "logs",
   "gridPos": { "h": 10, "w": 24, "x": 0, "y": 22 },
   "targets": [
    {
     "expr": "{job=\"containerlogs\"} |~ `(?i)Fail|Error` != `level=info`"
    }
   ]
  }
 ]
}