{
 "title": "Loki & Promtail",
 "time": { "from": "now-3h", "to": "now" },
 "refresh": "1m",
 "panels": [
  {
   "title": "Promtail version",
   "type": "stat",
   "gridPos": { "h": 4, "w": 2, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "promtail_build_info{job=\"promtail\"}\r\n",
     "legendFormat": "{{version}}"
    }
   ]
  },
  {
   "title": "Files in use",
   "type": "stat",
   "gridPos": { "h": 4, "w": 2, "x": 2, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "promtail_files_active_total", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "Total lines",
   "type": "stat",
   "gridPos": { "h": 4, "w": 8, "x": 4, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(promtail_read_lines_total{job=\"promtail\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Loki version",
   "type": "stat",
   "gridPos": { "h": 4, "w": 2, "x": 12, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "loki_build_info{job=\"loki\"}",
     "legendFormat": "{{version}}"
    }
   ]
  },
  {
   "title": "Go threads used",
   "type": "stat",
   "gridPos": { "h": 4, "w": 2, "x": 14, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    { "expr": "sum(go_threads)", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "Internal Log Messages",
   "type": "stat",
   "gridPos": { "h": 4, "w": 8, "x": 16, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "sum(loki_internal_log_messages_total)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Promtail entries count by status ",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    { "expr": "promtail_sent_entries_total", "legendFormat": "Sent Entries" },
    {
     "expr": "sum by(job) (promtail_read_lines_total)",
     "legendFormat": "Read Entries"
    },
    {
     "expr": "sum by(job) (promtail_dropped_entries_total)",
     "legendFormat": "Dropped entries"
    }
   ]
  },
  {
   "title": "Loki query latency [90%]",
   "type": "histogram",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "expr": "histogram_quantile(0.90, sum(rate(loki_logql_querystats_latency_seconds_bucket[$__range])) by (le))",
     "legendFormat": "Loki query latency "
    }
   ]
  },
  {
   "title": "Promtail duration of send requests",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 13 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "sum(rate(promtail_request_duration_seconds_count[$__range]))",
     "legendFormat": "Duration of send requests"
    }
   ]
  },
  {
   "title": "Loki query duration [90%]",
   "type": "histogram",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 13 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "expr": "histogram_quantile(0.90, sum(rate(logql_query_duration_seconds_bucket{job=\"loki\",instance=\"loki:3100\"}[$__range])) by (le))",
     "legendFormat": "Query duration"
    }
   ]
  }
 ]
}