server:
  http_listen_port: 3200
  grpc_listen_port: 0
  register_instrumentation: true

positions:
  filename: /tmp/positions.yaml

clients:
  - url: http://loki:3100/loki/api/v1/push

scrape_configs:
- job_name: system
  static_configs:
  - targets:
      - localhost
    labels:
      job: varlogs
      __path__: /var/log/*log

- job_name: journal
  journal:
    json: false
    max_age: 12h
    path: /var/log/journal
    labels:
      job: systemd-journal
  relabel_configs:
    - source_labels: ["__journal__systemd_unit"]
      target_label: "unit"
    - source_labels: ["__journal__hostname"]
      target_label: host
    - source_labels: ["__journal_priority_keyword"]
      target_label: level
    - source_labels: ["__journal_syslog_identifier"]
      target_label: syslog_identifier

- job_name: containers
  static_configs:
  - targets:
      - localhost
    labels:
      job: containerlogs
      __path__: /var/lib/docker/containers/*/*log
  pipeline_stages:
  - json:
      expressions:
        stream: stream
        attrs: attrs
        tag: attrs.tag
  - regex:
      expression: (?P<image_name>(?:[^|]*[^|])).(?P<container_name>(?:[^|]*[^|])).(?P<image_id>(?:[^|]*[^|])).(?P<container_id>(?:[^|]*[^|]))
      source: "tag"
  - labels:
      tag:
      stream:
      image_name:
      container_name:
      image_id:
      container_id:
  - metrics:
      log_lines_total:
        type: Counter
        description: "total number of log lines collected in containers"
        prefix: container
        max_idle_duration: 24h
        config:
          match_all: true
          action: inc
      log_bytes_total:
        type: Counter
        description: "total bytes of log lines collected in containers"
        prefix: container
        max_idle_duration: 24h
        config:
          match_all: true
          count_entry_bytes: true
          action: add