scrape_configs:
  - job_name: 'loki'
    static_configs:
      - targets: ['loki:3100']
  - job_name: 'promtail'
    static_configs:
      - targets: ['promtail:3200']
  - job_name: 'node-exporter'
    static_configs:
      - targets: ['node-exporter:9100']